name: Create a new issue
description: Create a new issue to suggest improvements in the docs or the website
body:
  - type: markdown
    attributes:
      value: |

        * For questions, check the [Community Forum](https:/forum.weaviate.io), or ask in [Slack](https://weaviate.io/slack).
        * Before you file an issue read the [Contributing guide](https://weaviate.io/developers/contributor-guide).
        * Check to make sure someone hasn't already opened a similar [issue](https://github.com/weaviate/weaviate-io/issues).

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a Code of Conduct that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)
          required: true

  - type: textarea
    attributes:
      label: Server Version
      description: |
        - What Weaviate Server are you running?
    validations:
      required: true
